version: "3.9"

services:
  bot:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://bot:bot@db/bot_db
    volumes:
      - .:/app

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db
      - wdb
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://bot:bot@db/bot_db
      - PYTHONPATH=/app/bot
      - WDB_NO_BROWSER_AUTO_OPEN=True
      - WDB_SOCKET_SERVER=wdb
    volumes:
      - .:/app

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=bot
      - POSTGRES_DB=bot_db
    volumes:
      - db-data:/var/lib/postgresql/data


  wdb:
    image: kozea/wdb:3.2.5
    ports:
      - 1984:1984

volumes:
  db-data:
