FROM python:3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest==7.4.2
RUN pip install pytest-asyncio==0.21.1
RUN pip install wdb

COPY bot bot
COPY tests tests

CMD ["pytest", "tests/"]
